version: "3.3"
services:
  katie:
    image: wyona/yanel-tomcat:3.1.1
    container_name: yanel
    restart: always
    volumes:
      - /home/wyona/yanel/logs:/yanel-logs
      - /home/wyona/yanel/configs:/yanel-configs
      - /home/wyona/yanel/realms:/realms
      - /home/wyona/yanel/resources:/resources
    ports:
      - 9090:8080
